FROM mcr.microsoft.com/dotnet/sdk:5.0 as base

WORKDIR /storingspace
COPY aspnet_storing .
RUN dotnet build
RUN dotnet publish -c Release -o out StoringApi.Service/StoringApi.Service.csproj

FROM mcr.microsoft.com/dotnet/aspnet:5.0

WORKDIR /publish
COPY --from=base storingspace/out .
CMD ["dotnet", "StoringApi.Service.dll"]