defaults:
  run:
    working-directory: aspnet_storing

jobs:
  build:
    name: building_storing
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test

  pack:
    needs:
      - build
      - test
    runs-on: ubuntu-20.04
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - run: docker image build -f ../dockerfiles/storingapi/dockerfile -t storingapi ..
      - run: docker image tag storingapi videoswithfriends/storingapi
      - run: docker push videoswithfriends/storingapi
      - run: docker logout

  deploy:
    needs: pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ZACH }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: video-repo-friends
          images: videoswithfriends/storingapi

on:
  push:
    branches:
      - main